version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
  form_obtainer:
    container_name: form_obtainer
    build: .
    hostname: form_obtainer
    environment:
      - collection=templates
      - database=form
      - host=mongo
      - user=user
      - password=password
      - port=27017
    ports:
      - "10000:10000"
